### ISSUE TITLE
测试房间是否已经开播

### ISSUE THREAD

**Issue by hleft** [THMonster/Revda#38]
经常想cli先判断一批直播间有没有开播， 再选择一个开播的直播间打开 

现在只能 `qlphelper -u <url>` , 如果没开播手动关掉

希望支持 `qlphelper --test <url>`,  先测试是否开播了

**Comment by THMonster** [comment]
没开播会自动退出的，你等个一分钟看看

**Comment by hleft** [comment]
@THMonster 有时只想打开一个开播的直播间， 不先测试可能会打开很多个还是得手动关掉啊。 如果不是同时开，轮流等一分钟要太久了

**Comment by THMonster** [comment]
不大清楚你的用途，不过凭我的感觉，可能你还是自己写个程序去满足你的需求比较好。

**Comment by THMonster** [comment]
有一些工具有你说的功能，你可以包个shell script结合起来用，为觉得我这就没必要加这个功能了

**Comment by hleft** [comment]
@THMonster 什么工具有这功能呢我去看看  (需求就是想和去到网站一样, 先看到开没开播再决定点不点开，而不是反过来先点开再看到开不开播..)

**Comment by THMonster** [comment]
那就奇怪了，如果你的需求只是这个，那gui不就能满足你了吗？gui不是会显示主播是否开播了吗？

**Comment by hleft** [comment]
@THMonster 感觉cli体验更好, 把直播间链接给rofi/dmenu选房间比较方便。 gui要开个新窗口用鼠标点，而且暗色主题出现gui的白窗口（也许这个主题可以改? 不过cli就省事了..）

**Comment by THMonster** [comment]
那你就参考我上面说的，自己套个脚本
