### ISSUE TITLE
Firefox插件商店没有Open With DMLive插件

### ISSUE THREAD

**Issue by RiverOnVenus** [THMonster/Revda#43]
[wiki](https://github.com/THMonster/Revda/wiki/2-%E8%BF%9B%E9%98%B6%E7%94%A8%E6%B3%95#firefox)中提到的[Open With DMLive](https://addons.mozilla.org/en-US/firefox/addon/open-with-dmlive/)插件在商店中没有。

![image](https://user-images.githubusercontent.com/79885139/170407533-82f4f705-1e0c-4666-83ed-a34f7f8a7d97.png)

**Comment by THMonster** [comment]
是没有，firefox不让我上架。我也没办法了，你从源码里装吧。

**Comment by RiverOnVenus** [comment]
哦哦，原来是这样。好的，谢谢。

**Comment by RiverOnVenus** [comment]
装好了，运行正常。

再次感谢你维护的这个项目，非常好用！
