### ISSUE TITLE
Can't open bilibili episode url

### ISSUE THREAD

**Issue by wsyxbcl** [THMonster/Revda#54]
Two demo URLs to reproduce:
```
> dmlive -u https://www.bilibili.com/bangumi/play/ep50511
[2023-03-15T10:17:02Z WARN  dmlive::streamfinder] real url not found, retry...
> dmlive -u https://www.bilibili.com/bangumi/play/ep674238
[2023-03-15T10:17:54Z WARN  dmlive::streamfinder] real url not found, retry..
```

It seems  [the function](https://github.com/THMonster/dmlive/blob/main/src/streamfinder/bilibili.rs#L105) parsing page info is outdated.

**Comment by THMonster** [comment]
It has been fixed in the  [dev](https://github.com/THMonster/dmlive/tree/dev) branch. Have a try if you're interested.
I will release a new version in the next few days.

**Comment by wsyxbcl** [comment]
Thanks, dev branch works, closing the issue.
