### ISSUE TITLE
弹幕消失了

### ISSUE THREAD

**Issue by unisgn** [THMonster/Revda#57]
以前是有弹幕的，不知道从啥时候起，弹幕没有了。命令行运行 dmlive 也可以看到打印的弹幕消息的。douyu, huya, bilibili 各个网站都是如此。
猜测可能是系统软件(ffmpeg, mpv)升级了，导致某些功能失效了。
ffmpeg verion n6.0
mpv version 0.36.0

**Comment by THMonster** [comment]
按j试试，可能是mpv更新后不默认选择字幕了

**Comment by unisgn** [comment]
按 j 确实把弹幕给切出来了。
顺便请教下这个有什么 mpv 选项可以让它变回以前的样子强制使用字幕吗?

**Comment by THMonster** [comment]
可以在mpv的配置文件里面加一行`sub=1`
这样就会在有字幕的情况下自动选择第一个字幕

**Comment by unisgn** [comment]
> 

加了这个选项总算恢复正常了，再次感谢。
