### ISSUE TITLE
GUI 界面异常

### ISSUE THREAD

**Issue by MrAru** [THMonster/Revda#59]
Revda version: archlinuxcn `revda-git` 5.3.1.r0.ga2b7778-1

异常描述：
打开 revda 后，无任何界面加载（见下图，灰色背景为 KDE 主题）。正常情况应该加载出白色界面。从命令行测试 `dmlive` 加载并播放视频正常。从命令行启动 `revda` 无任何异常信息输出，但也是同样的异常 GUI。
![image](https://github.com/THMonster/Revda/assets/26517155/9933460a-0b3b-45a7-b098-620c44842c7a)

revda 似乎用了 rust tauri 加载 webpage, 猜测是否可能与此相关？

**Comment by THMonster** [comment]
奇怪，我用的也是这个包，没有这个问题

**Comment by wanlce** [comment]
相同问题, 尝试过降级均无法正常。 只是web页面无法显示，点击空白的地方视频仍旧可以出现
➜  ~ paru -Qi revda-git
Installed From : archlinuxcn
名字           : revda-git
版本           : 5.3.1.r0.ga2b7778-1
桌面环境 Gnome
![image](https://github.com/THMonster/Revda/assets/55907021/f909fa9f-082b-48b7-8408-52fc25e57327)

**Comment by THMonster** [comment]
好怪，我换台电脑看看

**Comment by THMonster** [comment]
换了台电脑也没能复现，我之后看看升级下依赖发个新版本试试吧

**Comment by THMonster** [comment]
把依赖更新了下，不知道有没有用，或者你们也可以试试删一下在~/.cache/revda的缓存。

**Comment by wanlce** [comment]
> 把依赖更新了下，不知道有没有用，或者你们也可以试试删一下在~/.cache/revda的缓存。

已更新，且删除了~/.cache/revda  后依旧白屏
➜  ~ paru -Qi revda-git
Installed From : archlinuxcn
名字           : revda-git
版本           : 5.3.2.r0.gf6abde3-1

**Comment by THMonster** [comment]
我找了下，应该是上游的问题
https://github.com/tauri-apps/tauri/issues/7927
https://github.com/tauri-apps/tauri/issues/5143
其中有提到用这个环境变量`WEBKIT_DISABLE_COMPOSITING_MODE=1`能解决这个问题

**Comment by MrAru** [comment]
> 我找了下，应该是上游的问题 [tauri-apps/tauri#7927](https://github.com/tauri-apps/tauri/issues/7927) [tauri-apps/tauri#5143](https://github.com/tauri-apps/tauri/issues/5143) 其中有提到用这个环境变量`WEBKIT_DISABLE_COMPOSITING_MODE=1`能解决这个问题

Confirmed. 确实是上游问题，感谢排查！

**Comment by MrAru** [comment]
> > > 我找了下，应该是上游的问题 [tauri-apps/tauri#7927](https://github.com/tauri-apps/tauri/issues/7927) [tauri-apps/tauri#5143](https://github.com/tauri-apps/tauri/issues/5143) 其中有提到用这个环境变量`WEBKIT_DISABLE_COMPOSITING_MODE=1`能解决这个问题
> > 
> > 
> > Confirmed. 确实是上游问题，感谢排查！
> 
> 那加这个环境变量能解决你的问题吗？

可以，带环境变量之后界面正常。
