### ISSUE TITLE
b站直播只有低画质流

### ISSUE THREAD

**Issue by THMonster** [THMonster/Revda#60]
b站更改了他们的api，以后大概率不登录看不了原画了。

**Comment by THMonster** [comment]
https://github.com/SocialSisterYi/bilibili-API-collect/issues/846

**Comment by THMonster** [comment]
https://github.com/SocialSisterYi/bilibili-API-collect/issues/846

**Comment by lu0se** [comment]
config写bcookie好像也不能看原画

**Comment by THMonster** [comment]
> config写bcookie好像也不能看原画

当然不能啊，因为我还没修。原来的那个cookie是给b站视频用的。

**Comment by THMonster** [comment]
新版本应该修复了这个问题
