### ISSUE TITLE
无法观看虎牙直播了

### ISSUE THREAD

**Issue by unisgn** [THMonster/Revda#61]
前两天还好好的，这两天不知道他们更新了啥，观看不了了。

**Comment by THMonster** [comment]
虎牙好像一直有类似问题，我以前偶尔观测到，我找个机会修一下吧

**Comment by unisgn** [comment]
今天又尝试打开虎牙直播试了下，开始一两秒还出现了图像，之后画面就一直卡着动不了。控制日志有一条信息：
WARN dmlive::streamer::flv connection too slow。

**Comment by THMonster** [comment]
新版本应该修好了，可以试试看
