### ISSUE TITLE
源码安装，编译成功，链接失败

### ISSUE THREAD

**Issue by fuermobai** [THMonster/Revda#64]
发行版: gentoo
桌面: xfce4
安装依赖后，编译成功，链接错误，具体内容如下：
_cmake -DCMAKE_BUILD_TYPE=Release .._

CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- The C compiler identification is GNU 13.2.1
-- The CXX compiler identification is GNU 13.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Cargo: /usr/bin/cargo (found version "1.75.0") 
-- Found Rust: /usr/bin/rustc (found version "1.75.0") 
-- Configuring done (0.5s)
-- Generating done (0.0s)
-- Build files have been written to: /home/libre/Downloads/Revda/build

make
[ 50%] Generating /home/libre/Downloads/Revda/dmlive/target/release/dmlive
   Compiling proc-macro2 v1.0.78
   Compiling unicode-ident v1.0.12
   Compiling version_check v0.9.4
   ...
   Finished release [optimized] target(s) in 2m 38s
[ 50%] Built target dmlive-bin
[100%] Generating src-tauri/target/release/revda
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 1.47s.
yarn run v1.22.19
$ vue-tsc --noEmit && vite build
vite v4.4.10 building for production...
✓ 1406 modules transformed.
dist/index.html                   0.48 kB │ gzip:   0.30 kB
dist/assets/index-54e53519.css  325.02 kB │ gzip:  44.24 kB
dist/assets/index-678862f7.js   889.89 kB │ gzip: 284.22 kB

(!) Some chunks are larger than 500 kBs after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
✓ built in 6.74s
Done in 18.50s.
yarn run v1.22.19
$ /home/libre/Downloads/Revda/node_modules/.bin/tauri build
   Compiling proc-macro2 v1.0.78
   Compiling unicode-ident v1.0.12
   ...
   Compiling tauri-plugin-single-instance v0.0.0 (https://github.com/tauri-apps/plugins-workspace?branch=v1#056a458d)
error: linking with `cc` failed: exit status: 1
  |
  = note: LC_ALL="C" PATH="/opt/rust-bin-1.75.0/lib/rustlib/x86_64-unknown-linux-gnu/bin:/tmp/yarn--1711286465764-0.010662844484932599:/home/libre/Downloads/Revda/node_modules/.bin:/home/libre/.config/yarn/link/node_modules/.bin:/home/libre/.yarn/bin:/usr/libexec/lib/node_modules/npm/bin/node-gyp-bin:/usr/lib/node_modules/npm/bin/node-gyp-bin:/usr/bin/node_modules/npm/bin/node-gyp-bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/bin:/usr/lib/llvm/17/bin" VSLANG="1033" "cc" "-m64" "/tmp/rustcZZRz5X/symbols.o" "/home/libre/Downloads/Revda/src-tauri/target/release/deps/app-d245c8fc22de079b.app.2ae509bd028b9394-cgu.00.rcgu.o" "-Wl,--as-needed" "-L" "/home/libre/Downloads/Revda/src-tauri/target/release/deps" "-L" "/home/libre/Downloads/Revda/src-tauri/target/release/build/ring-7e6bf445f2d4f6e8/out" "-L" "/opt/rust-bin-1.75.0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/tmp/rustcZZRz5X/libring-f801baddba9f4e7b.rlib" "/opt/rust-bin-1.75.0/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-8e138eaf26ebb4a8.rlib" "-Wl,-Bdynamic" "-lgtk-3" "-lgdk-3" "-lharfbuzz" "-lpangocairo-1.0" "-lpango-1.0" "-latk-1.0" "-lcairo" "-lcairo-gobject" "-lgdk_pixbuf-2.0" "-lsoup-2.4" "-lgmodule-2.0" "-lgio-2.0" "-ljavascriptcoregtk-4.0" "-lglib-2.0" "-lgobject-2.0" "-lwebkit2gtk-4.0" "-lgmodule-2.0" "-lgio-2.0" "-lglib-2.0" "-lgobject-2.0" "-lsoup-2.4" "-lgobject-2.0" "-lglib-2.0" "-ljavascriptcoregtk-4.0" "-lharfbuzz" "-lpangocairo-1.0" "-lpango-1.0" "-lgdk_pixbuf-2.0" "-lcairo-gobject" "-lcairo" "-lglib-2.0" "-lgobject-2.0" "-lgdk-3" "-ldl" "-lgobject-2.0" "-lgdk-3" "-lharfbuzz" "-lpangocairo-1.0" "-lpango-1.0" "-latk-1.0" "-lcairo" "-lcairo-gobject" "-lgdk_pixbuf-2.0" "-lgio-2.0" "-lglib-2.0" "-lgobject-2.0" "-lgtk-3" "-lgobject-2.0" "-lglib-2.0" "-latk-1.0" "-lharfbuzz" "-lpangocairo-1.0" "-lpango-1.0" "-lgdk_pixbuf-2.0" "-lcairo-gobject" "-lcairo" "-lglib-2.0" "-lgobject-2.0" "-lgdk-3" "-lgobject-2.0" "-lglib-2.0" "-lharfbuzz" "-lpango-1.0" "-lgobject-2.0" "-lglib-2.0" "-lgdk_pixbuf-2.0" "-lgobject-2.0" "-lglib-2.0" "-lgio-2.0" "-lcairo" "-lgobject-2.0" "-lglib-2.0" "-lcairo-gobject" "-lglib-2.0" "-lgobject-2.0" "-lglib-2.0" "-lgobject-2.0" "-lssl" "-lcrypto" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-z,noexecstack" "-L" "/opt/rust-bin-1.75.0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/home/libre/Downloads/Revda/src-tauri/target/release/deps/app-d245c8fc22de079b" "-Wl,--gc-sections" "-pie" "-Wl,-z,relro,-z,now" "-nodefaultlibs"
  = note: /usr/lib/gcc/x86_64-pc-linux-gnu/13/../../../../x86_64-pc-linux-gnu/bin/ld: /home/libre/Downloads/Revda/src-tauri/target/release/deps/app-d245c8fc22de079b.app.2ae509bd028b9394-cgu.00.rcgu.o: in function `tauri_runtime_wry::handle_user_message':
          app.2ae509bd028b9394-cgu.00:(.text._ZN17tauri_runtime_wry19handle_user_message17h63e0f29a6a503413E+0x3595): undefined reference to `gdk_wayland_window_get_wl_surface'
          collect2: error: ld returned 1 exit status
          
  = note: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)

error: could not compile `app` (bin "app") due to previous error
       Error failed to build app: failed to build app
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
make[2]: *** [CMakeFiles/revda-bin.dir/build.make:75: src-tauri/target/release/revda] Error 1
make[1]: *** [CMakeFiles/Makefile2:138: CMakeFiles/revda-bin.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

_eselect gcc list_
 [1] x86_64-pc-linux-gnu-13 *

**Comment by fuermobai** [comment]
切换成gcc12，一样的问题。

**Comment by THMonster** [comment]
你看看会不会是这个问题
https://github.com/ffplayout/ffplayout/issues/580#issuecomment-2041338122

**Comment by fuermobai** [comment]
> 你看看会不会是这个问题 [ffplayout/ffplayout#580 (comment)](https://github.com/ffplayout/ffplayout/issues/580#issuecomment-2041338122)

谢谢！我回去晚上试试，然后过来反馈。
